// components/NavBar/NavBar.vue
<template>
  <nav class="nav" :class="!isDark ? 'nav--light' : 'nav--dark'">
    <div class="nav-left">
      <icon-button
        :icon="{
          src: !isDark ? '/logo-light.png' : '/logo-dark.png',
          height: 56,
          width: 56,
          alt: 'Logo',
        }"
        :dark="isDark"
      />
    </div>
    <div class="nav-right">
      <icon-link
        class="nav-right__item"
        href="https://www.linkedin.com/in/binodnepali"
        target="_blank"
        :icon="{
          src: !isDark
            ? 'assets/icons/light/linkedin.svg'
            : 'assets/icons/dark/linkedin.svg',
          height: 36,
          width: 36,
          alt: 'linkedin',
        }"
      />
      <icon-link
        class="nav-right__item"
        href="https://github.com/binodnepali"
        target="_blank"
        :icon="{
          src: !isDark
            ? 'assets/icons/light/github.svg'
            : 'assets/icons/dark/github.svg',
          height: 36,
          width: 36,
          alt: 'github',
        }"
      />
      <icon-button
        class="nav-right__item"
        :dark="isDark"
        :icon="{
          src: !isDark
            ? 'assets/icons/light/light_mode.svg'
            : 'assets/icons/dark/dark_mode.svg',
          height: 36,
          width: 36,
          alt: 'theme mode',
        }"
        :handleOnClick="handleOnThemeMode"
      />
    </div>
  </nav>
</template>
<script setup lang="ts">
import { ref } from 'vue';

import '@/components/IconButton/IconButton.vue';
import '@/components/IconLink/IconLink.vue';

const isDark = ref(false);
const handleOnThemeMode = () => {
  isDark.value = !isDark.value;
};
</script>
<style lang="sass" scoped>
.nav
  display: flex
  min-height: var(--size-8)

.nav--light
  background-color: var(--primary-color)

.nav--dark
  background-color: var(--primary-dark-color)

.nav-left
  flex-grow: 1

.nav-right
  display: flex

.nav-right__item
  margin: var(--size-2)
</style>

// islands/Navbar.tsx
import { useState } from "preact/hooks";

import { Button } from "../components/Button.tsx";
import { Link } from "../components/Link.tsx";

import { IconLinkedIn } from "../components/IconLinkedIn.tsx";
import { IconEmail } from "../components/IconEmail.tsx";
import { IconGitHub } from "../components/IconGitHub.tsx";

const links = [
  {
    href: "https://www.linkedin.com/in/binodnepali",
    label: "linkedin",
    icon: <IconLinkedIn className={"fill-current"} />,
  },
  {
    href: "mailto:nepalibinod9@gmail.com",
    label: "email",
    icon: <IconEmail className={"fill-current"} />,
  },
  {
    href: "https://github.com/binodnepali/portfolio",
    label: "github",
    icon: <IconGitHub className={"fill-current"} />,
  },
];

export default function Navbar() {
  const [isDark, setIsDark] = useState(false);

  return (
    <nav class="h-14 bg- flex items-center px-4">
      <div class="flex flex-grow-1 items-center ">
        <Link
          class="font-semibold text-xl text-primary-on-light-500"
          href="/"
          label="b.n"
        >
          B.N
        </Link>
      </div>

      <div class="flex gap-4">
        {links.map(({ href, label, icon }) => (
          <Link
            href={href}
            key={href}
            label={label}
            target="_blank"
          >
            {icon}
          </Link>
        ))}
      </div>

      <Button class="ml-2" onClick={() => setIsDark(!isDark)}>
        <div class="flex">
          <span class="material-symbols-outlined">
            {isDark ? "dark_mode" : "light_mode"}
          </span>
        </div>
      </Button>
    </nav>
  );
}
